name: weather_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  http: ^1.5.0
  intl: ^0.20.2
  lottie: ^3.3.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_logos/
    - assets/weather_images/
